#!/bin/bash
if [ -n "$BASH_VERSION" ]; then
  if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
  fi
fi

if [ -d "$HOME/bin" ] ; then
  export PATH="$HOME/bin:$PATH"
fi

export GOPATH=/gopath
export PATH=$PATH:$GOPATH/bin
